### PR TITLE
Ashrith

### PR DESCRIPTION
**Pull request by ashrithjacob**
Added:
- jupyter notebook to run on colab
- added statements to display images

### CODE REVIEW

**Comment by ashrithjacob** [comment]
Hi psyrocloud,
I'm Ashrith and I'm working on a project that uses the MS_SSIM_L1 loss. I thought that since It's a useful loss function, we could make it easier for people to use. I've added a few basic changes. I can also update the README if you wish.

**Comment by 1238880p** [comment]
Excuse me, author: It seems that the source code for MS-SSIM and L1 weighting does not perform downsampling on the image. Is an operation similar to downsampling achieved through sigma

**Comment by psyrocloud** [comment]
> Excuse me, author: It seems that the source code for MS-SSIM and L1 weighting does not perform downsampling on the image. Is an operation similar to downsampling achieved through sigma

Yes, the formulae are following the cited references.

**Review by psyrocloud — APPROVED** [review]
Thank you for adding the codes.

**Review by psyrocloud — COMMENTED** [review]
Let us keep the code as simple as possbile, thank you.

**Review by psyrocloud — COMMENTED** [review]
Also, let us keep the code as simple as possible. Thanks.

**Pull request merged**
